### ISSUE TITLE
css doesn't work

### ISSUE THREAD

**Issue by eetsceeck1** [phppgadmin/phppgadmin#133]
hi,
no css loaded with the script, its only me or other people have the same problem as well?
i did try downloading also the other compressed files, none of them works, 

i did check the css path in the included files and all looks okay, the theme folder is included

thank you

**Comment by xzilla** [comment]
Well, presumably it is you, and there really aren't enough details to help... What browser are you using? What web server are you serving with? Which version of PPA are you running? Etc...

**Comment by eetsceeck1** [comment]
Hi, 
thank you very much for a quick response, 
I did download the zip straight from GitHub, 
i had been set the whole folder under xampp independently as a system folder with the same principle as phpmyadmin (for mysql) is installed, and added the right parameters to xampp.conf, and when i tries to load the index.php,
i am getting a page with drop down options and broken jpg/png links, looks like no css being loaded together with the script, 

i was thinking maybe this is happening cause its under the system not externally through the htdocs, so i did commented out the xampp.conf and i did set the script in the htdocs and tried to access it on localhost, 
i dont see the same page the same way as before with the drop down now, i see one pane at the left side and at the middle a page space, both are empty and with the browser's icon indicate that is not reachable, and its says refused to connect, 
i did check the if there is no mistake in the config.inc about the server and port both are right, localhost and the default port 5432 of postgre, 
i am using pgadmin4 just to be sure the server is running and accessible, and it is, 

you did mentioned at the install file something about installation which i am not sure where is, there is no nor install folder or file in the whole folder, am i missing something? 

thank you for your help

**Comment by skaag** [comment]
I know this is old but here's what may happen to some of you if you came here with a similar problem:
When you install nginx or apache, the user it runs as will typically be something like 'www-data' or some non-root user. If you run phpPgAdmin from a folder under `/var/www/` (which is typically owned by the web user), then it may work fine and CSS won't be missing.
If however you create a unique user for phpPgAdmin (as you should!), let's say something like `pgadmin` and you host the files in `/home/pgadmin/sites/pgadmin.yourdomain.com/public_html` then nginx can no longer read your CSS/JS files.
It will run the PHP files just fine though! Why? because if you run php-fpm then you've set the pool to the correct user (in this case `pgadmin:pgadmin`) and therefor the PHP process will have the proper access and execute the PHP scripts.
The result is that the PHP scripts are executed fine, but nginx can't access the static assets, and that's how you end up with a "naked" phpPgAdmin.
