### ISSUE TITLE
Can't login with created user

### ISSUE THREAD

**Issue by EdvaldoAFilho** [phppgadmin/phppgadmin#169]
I already made the phppgadmin works with php 8.1 following this https://github.com/phppgadmin/phppgadmin/issues/119#issuecomment-751410900

Now everything seens work good (logged as postgres) but when i try to login with a new created user the system give me Login Failed

![image](https://user-images.githubusercontent.com/72243003/218327782-72e3365f-e2f3-40a3-bb4e-e5b3809ae68e.png)

**In postgres :**

![image](https://user-images.githubusercontent.com/72243003/218327835-3e47fcfa-e636-42c7-ab86-67dbd9ba1c50.png)

**Roles (logged as 'postgres')**

![image](https://user-images.githubusercontent.com/72243003/218327937-9e34dc8a-9380-4c2c-a4e5-b573377c0a1d.png)

I'm newbie and don't have much experience in server configuration, I tried to change the **pg_hba.conf** file :

![image](https://user-images.githubusercontent.com/72243003/218328255-0cecec01-1218-43fe-9b3d-378109971f14.png)

Taking that last print I note the line : 
`local      all      all      md5`
Does this make the previous lines redundant? 

And why i cant loggin with my new user ?

**Comment by xzilla** [comment]
I reckon you have resolved this, but in general:
1. make sure you can login with cardproot user using psql using the same connection parameters that are setup in your config.inc.php 
2. Verify your postgres logs are configured to produce login failures and see what error message you get when trying to log in via ppa. 

Closing this given the time lapse since originally posted, but if you want to revisit it, please reopen.
