### ISSUE TITLE
Sequence issues

### ISSUE THREAD

**Issue by ecoyork** [phppgadmin/phppgadmin#68]
We installed the latest version of phppgadmin however we're having issues viewing sequences. Has anyone seen anything similar?
ERROR:  relation "pg_catalog.pg_sequence" does not exist

I'd like to note it's been awhile since i viewed the sequences, but a few months ago i feel like this wasn't an issue.

**Comment by ecoyork** [comment]
I'll note we can run a SQL command SELECT last_value FROM sequence_id; once we click on the table in phppgadmin and then run sql. If we try to browse we get errors.

**Comment by ecoyork** [comment]
PostgreSQL 9.2.24 is the version this seems to do queries that are not compatible with our current version. Is there a patch to make the newest version work with older versions of postges ?

**Comment by xzilla** [comment]
I danced with this code in order to fix it on recent releases and regretted that choice, but a bunch of the sequence internals have changed over recent releases, so not much choice there. You can check out the resultant commit at:  https://github.com/phppgadmin/phppgadmin/commit/2355dc514354ebb78d14a9e27d2dcc20da96e428

I suspect what you need to do is take the old code and make a new method in 92/93 or similar versions and test that it fixes it and still works on the nearby releases. I don't have any 92/93 servers set up for testing / debugging though, so probably not going to do the work myself in the absence of a paying client, but I'd accept a patch if you get it working.
