### ISSUE TITLE
Some few code spelling errors in  phpPgAdmin-7.12.0.tar.bz2

### ISSUE THREAD

**Issue by jschleus** [phppgadmin/phppgadmin#73]
As administrator of a FOSS server I have just added a new feature: Source code misspelling error checks for the supported software  packages using the command line program `codespell`. 

One of the first checks was just done for  `phpPgAdmin-7.12.0.tar.bz2`. The output of the analysis can be found here: https://fossies.org/linux/www/phpPgAdmin-7.12.0.tar.bz2/codespell.html 

A hint: Clicking on a red colored spelling error in the "top" list let you jump to the first according match in the actual spelling error occurrence list. Clicking on a matching member file  let you browse that file while jumping to the according line (with a red colored line number; but in some cases the misspelled word may be in the adjacent lines).

I know it's not an important issue and you can ignore it but if you found wrong matches (false positives) please let me know it so that I can force a new improved check.

**Comment by xzilla** [comment]
Thanks so much for this feedback. I've merged a patch based on this work (https://github.com/phppgadmin/phppgadmin/commit/80e18adc0b288f471e3284be53e1b8368811f877), but if you are willing to do another round of tests, I'd be interested to see what else it picks up. Thanks again for the submission!

**Comment by jschleus** [comment]
Hmm, unfortunately it's currently not easy to create such a report for a package not supported on fossies.org. So I analyzed current master on another system and made the results available under https://fossies.org/linux/www/phpPgAdmin-7.12.0.tar.bz2/codespell_20191031_2158.html

But be aware that some of the links may fail or point to slightly wrong code parts since on the Fossies server the source code of the current release is in use. But the list of spelling errors and the according line numbers should be correct.

**Comment by nirgal** [comment]
There's a few typo left.

I checked PL/I syntax, and SUPERCEDE is not a keyword. Neither is SUPERSEDE. There are a lot of new PL/I keywords, but I guess this is far beyond the scope of that report.

Also, I'm lost regarding the use of $_PATERN_$ in the SQL...
https://fossies.org/linux/test/phppgadmin-master.b8140fe.tar.gz/phppgadmin-master/classes/database/Postgres.php?M=3560#l_3560 uses the obscure syntax substring(... from ...) described in https://www.postgresql.org/docs/11/functions-matching.html for pattern matching, but I can't begin to understand how $_PATERN_$ is replaced somewhere, especially with a typo (patern rather than pattern) !

Regarding like 3560 of Postgres.php, using an existing database (kmail), I get:
```
SELECT DISTINCT
        c.conkey               
        FROM pg_catalog.pg_constraint AS c
        JOIN pg_catalog.pg_class AS r ON (c.conrelid=r.oid)
        JOIN pg_catalog.pg_namespace AS ns ON (r.relnamespace=ns.oid)
```
returning
```
 conkey 
--------
 {1}
 {1,2}
 {2}
 {3}
 {4}
 {5}
 {6}
 {7}
(8 rows)
```
Then
```
SELECT DISTINCT
        array_dims(c.conkey)               
        FROM pg_catalog.pg_constraint AS c
        JOIN pg_catalog.pg_class AS r ON (c.conrelid=r.oid)
        JOIN pg_catalog.pg_namespace AS ns ON (r.relnamespace=ns.oid)
```
returning
```
 array_dims 
------------
 [1:1]
 [1:2]
(2 rows)
```

Then 
```
SELECT DISTINCT
        SUBSTRING(array_dims(c.conkey) FROM  $patern$^\[.*:(.*)\]$$patern$) as nb
        FROM pg_catalog.pg_constraint AS c
        JOIN pg_catalog.pg_class AS r ON (c.conrelid=r.oid)
        JOIN pg_catalog.pg_namespace AS ns ON (r.relnamespace=ns.oid)
```
returning
```
 nb 
----
 1
 2
(2 rows)
```
But so does
```
SELECT DISTINCT
        SUBSTRING(array_dims(c.conkey) FROM ':(.*)]$') as nb
        FROM pg_catalog.pg_constraint AS c
        JOIN pg_catalog.pg_class AS r ON (c.conrelid=r.oid)
        JOIN pg_catalog.pg_namespace AS ns ON (r.relnamespace=ns.oid)
```
(This takes everything between the ':' and the ']' at the end of the string. )

Does anyone understand this ill-spelled \$PATERN\$ on line 3560? It seems like it could be replaced by \$PATTERN\$, by \$XXX\$, or more logically by a single quote!

**Comment by xzilla** [comment]
Aside from the typo, this looks like pretty standard dollar-quoting syntax to me: https://www.postgresql.org/docs/11/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

Especially when looking at the commit where it came in: https://github.com/phppgadmin/phppgadmin/commit/13eb806880941b93ecc7671fc66e4f20a79069c8

FWIW, I think using the dollar quoting in general (vs actual quotes) does make it more legible.
